version: "3"
services:
  project_main: # Nginx
    container_name: docker_main
    build: ../nginx/
    volumes:
      - ../nginx:/etc/nginx/conf.d/
      - ../..:/projects
    ports:
      - "80:80"
    links:
      - "project_golang"
    restart: always
  project_golang: # Golang
    container_name: docker_golang
    volumes:
      - ../..:/projects
    build:
      context: ../../
      dockerfile: Dockerfile
    restart: always
