image: golang:latest

test:
  stage: test
  script:
    - echo "everything OK!"
staging:
  stage: deploy
  script:
    - echo "Staging everything OK!"
  only:
    - master
production:
  stage: deploy
  only:
    - master
  before_script:
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - bash .gitlab-deploy-dev.sh
