version: "3"
services:
  web:
    container_name: docker_web
    build: ./nginx/
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - .:/app
    ports:
      - "80:80"
    links:
      - "golang"
  golang:
    container_name: docker_golang
    build: ./
    volumes:
      - .:/app
    links:
      - "mongo"
  mongo:
    image: mongo
    container_name: "docker_mongodb"
    ports:
      - "27017:27017"
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8500:8500"
    container_name: jenkins
    volumes:
      - ~/deploy/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    
