version: "3"
services:
  web:
    build: ./nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - .:/app
    ports:
      - "80:80"
    links:
      - "golang"
  golang:
    container_name: docker_golang
    build: ./
    volumes:
      - .:/app
    env_file:
      - .env.develop
    links:
      - "mongo"
  mongo:
    image: mongo
    container_name: "docker_mongodb"
    ports:
      - "27017:27017"
